version: '3'

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5438:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data:rw
    env_file:
      - ./.env
volumes:
  postgres-db: