"""create Form

Revision ID: ac1eb229f126
Revises: a71dc148222b
Create Date: 2024-06-19 21:22:05.197404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1eb229f126'
down_revision: Union[str, None] = 'a71dc148222b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronic_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('family_status', sa.Enum('married', 'single', 'divorced', 'widowed', name='familystatusenum'), nullable=False),
    sa.Column('occupation_status', sa.Enum('hired', 'jobless', 'studying', 'retired', name='occupationstatusenum'), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('health_issues', sa.Text(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('city_of_casting', sa.Enum('Almaty', 'Astana', 'Turkistan', 'Kyzylorda', 'Aktau', 'Aktobe', 'Kostanai', 'Kokshetau', 'Pavlodar', 'Oskemen', name='cityofcastingenum'), nullable=False),
    sa.Column('final_participation', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_id'), 'form', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_id'), table_name='form')
    op.drop_table('form')
    # ### end Alembic commands ###
